if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

## Fonts config
for dir in `ls -d -1 /usr/local/share/fonts/`; do
    xset fp+ "/usr/local/lib/X11/fonts/$m"
done

# GPG agent
gpg-agent --enable-ssh --daemon >/dev/null 2>&1
SSH_AUTH_SOCK=/home/peter/.gnupg/S.gpg-agent.ssh; export SSH_AUTH_SOCK;

xmonad
