if [ -x /usr/local/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
        eval `dbus-launch --sh-syntax --exit-with-session`
fi

## Fonts config
for dir in `ls -d -1 /usr/local/share/fonts/`; do
    xset fp+ "/usr/local/lib/X11/fonts/$m"
done

xmonad
