;;; init.el --- User configuration file for Emacs
;;
;; This configuration was generated by ChatGPT 4.
;;

;; Initialize package sources
(require 'package)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))

(package-initialize)

;; Ensure 'use-package' is installed; install it if it's not
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; General Settings
(setq inhibit-startup-message t)  ;; No splash screen
(scroll-bar-mode -1)              ;; Disable scroll bars
(tool-bar-mode -1)                ;; Disable tool bar

;; Use Solarized light theme
(use-package solarized-theme
  :ensure t
  :config
  (load-theme 'solarized-light t))

;; Programming language support
;; Julia
(use-package julia-mode
  :ensure t)

;; Python
(use-package python-mode
  :ensure t)

;; Racket
(use-package racket-mode
  :ensure t)

;; ESS for R
(use-package ess
  :ensure t)

;; Predictive autocompletion
(use-package company
  :ensure t
  :hook (after-init . global-company-mode)
  :config
  (setq company-idle-delay 0.2
        company-minimum-prefix-length 2))

;; For better interface and icons in the completion dropdown
(use-package company-box
  :ensure t
  :hook (company-mode . company-box-mode))

;; Magit for Git integration
(use-package magit
  :ensure t)

;; Org mode and Babel
(use-package org
  :ensure t
  :config
  ;; Org Babel languages
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((julia . t)
     (python . t)
     (R . t))))

;; Paredit for Lisp-based modes
(use-package paredit
  :ensure t
  :hook ((emacs-lisp-mode . paredit-mode)
         (eval-expression-minibuffer-setup . paredit-mode)
         (ielm-mode . paredit-mode)
         (lisp-mode . paredit-mode)
         (lisp-interaction-mode . paredit-mode)
         (scheme-mode . paredit-mode)
         (racket-mode . paredit-mode)))  ; Paredit for Racket

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   '(paredit magit company-box company ess racket-mode python-mode julia-mode solarized-theme use-package)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
